import React, { useEffect } from 'react'
import Head from 'next/head'
import PokemonGrid from '../components/PokemonGrid'

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Pokemon Grid</p>
      <PokemonGrid />
    </>
  )
}
